# Generated by Django 3.0 on 2020-03-19 19:31

import catalog.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=catalog.helpers.get_unique_filename),
        ),
    ]
